#spring:
#  datasource:
#    url: jdbc:mysql://192.168.182.129:3306/test?characterEncoding=utf8
#    username: root
#    password: A123456
#  jpa:
#    database: MYSQL
#    show-sql: true
#  #Hibernate ddl auto (validate|create|create-drop|update)
#    hibernate:
#      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect